apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
  containers:
  - name: springboot
    image: josephrodriguez/springboot-starterkit