apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: kafka
spec:
  storageClassName: local-storage
  capacity:
    storage: "100Mi"
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/var/lib/kafka"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
