apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-claim
  namespace: kafka
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"