apiVersion: v1
kind: Service
metadata:
  labels:
    run: ngrok
  name: multipod-service
spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 80
  - name: port-2
    port: 4040
    protocol: TCP
    targetPort: 4040
  selector:
    run: ngrok
