apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ngrok
  name: multipod
spec:
  containers:
  - image: nginx:1.23.0-alpine
    name: web
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    volumeMounts:
    - name: content-volume
      mountPath: "/var/cache/nginx"
  - image: josephrodriguez/ngrok
    name: ngrok
    imagePullPolicy: IfNotPresent
    envFrom:
    - secretRef:
        name: ngrok
    args:
    - "http"
    - "80"
    - "--authtoken=$(AUTH_TOKEN)"
    - "--log=stdout"
    ports:
    - containerPort: 4040
  volumes:
  - name: content-volume
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
