apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
          - key: kubernetes.io/disktype
            operator: In
            values:
            - ssd            
  containers:
  - name: springboot
    image: josephrodriguez/springboot-starterkit