apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot
  name: anti-affinity-2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - web
              topologyKey: kubernetes.io/hostname          
      containers:
      - image: josephrodriguez/springboot-starterkit
        name: web-application