---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: josephrodriguez/springboot-starterkit
        name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - image: redis:alpine
        name: redis